name: Backend Push

on:
  workflow_run:
    workflows: ['CI-CD Nest.js']
    types:
      - completed

jobs:
  push-main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone the central repository
        run: |
          git clone https://YannMorvan:${{ secrets.EIP_GITHUB_PAT }}@github.com/YannMorvanOrg/app.git _app

      - name: Pull/Add Backend as subtree
        working-directory: _app
        run: |
          if [ -d "backend" ]; then
            git subtree pull --prefix=backend https://YannMorvan:${{ secrets.EIP_GITHUB_PAT }}@github.com/YannMorvanOrg/backend.git main --squash
          else
            git subtree add --prefix=backend https://YannMorvan:${{ secrets.EIP_GITHUB_PAT }}@github.com/YannMorvanOrg/backend.git main --squash
          fi

      - name: Push changes
        working-directory: _app
        run: |
          git push origin main
