name: Frontend Push

on:
  push:
    branches:
      - main

jobs:
  push-main:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone the central repository
        run: |
          git clone https://YannMorvan:${{ secrets.EIP_GITHUB_PAT }}@github.com/YannMorvanOrg/app.git _app

      - name: Pull/Add Frontend as subtree
        working-directory: _app
        run: |
          if [ -d "frontend" ]; then
            git subtree pull --prefix=frontend https://YannMorvan:${{ secrets.EIP_GITHUB_PAT }}@github.com/YannMorvanOrg/frontend.git main --squash
          else
            git subtree add --prefix=frontend https://YannMorvan:${{ secrets.EIP_GITHUB_PAT }}@github.com/YannMorvanOrg/frontend.git main --squash
          fi

      - name: Push changes
        working-directory: _app
        run: |
          git push origin main
